% ================= REAL-TIME MPPT WITH POST-ANALYSIS ================== %
clear; clc;

% === MPPT Parameters ===
TaC = 25;                 % Temperature (°C)
C   = 0.5;                % P&O step
Va  = 31;                 % Initial PV voltage
Suns = 0.2;               % Initial irradiance
Ia = PV_model(Va,Suns,TaC);
Pa = Ia*Va;
Vref_new = Va + C;

% Storage arrays for post-analysis
Va_array = [];
Pa_array = [];
Suns_array = [];

% === Irradiance profile ===
Suns_curve = [0 0.1; 1 0.3; 2 0.7; 3 1.0; 4 0.9; 5 0.6; 6 1.2; 7 1.4];
xi = 1:200;
yi = interp1(Suns_curve(:,1), Suns_curve(:,2), xi, 'pchip');

% === Pre-compute voltage range for P-V curves ===
Vline = 0:0.5:40;

% ==================== REAL-TIME FIGURE ======================= %
figure('Name','Real-Time MPPT Animation');
hold on; grid on;

% Initial P-V curve
Iline = PV_model(Vline, yi(1), TaC);
Pline = Vline.*Iline;
pv_curve = plot(Vline, Pline,'b-','LineWidth',2);

xlabel('Voltage (V)','FontSize',14)
ylabel('Power (W)','FontSize',14)
title('Real-Time MPPT Tracking (P&O)','FontSize',15)

% Animated marker
mppt_point = plot(Va,Pa,'ro','MarkerSize',10,'MarkerFaceColor','r');
legend('P-V Curve','MPPT Point','Location','best');

% ===================== MPPT LOOP ANIMATION =================== %
for i=1:length(yi)
    Suns = yi(i);
    
    % UPDATE P-V CURVE FOR CURRENT IRRADIANCE
    Iline = PV_model(Vline, Suns, TaC);
    Pline = Vline.*Iline;
    set(pv_curve,'YData',Pline);
    
    % MPPT ALGORITHM
    Va_new = Vref_new;
    Ia_new = PV_model(Va_new,Suns,TaC);
    Pa_new = Va_new * Ia_new;
    deltaP = Pa_new - Pa;
    
    % P&O DECISION
    if deltaP > 0
        if Va_new > Va, Vref_new = Va_new + C;
        else,          Vref_new = Va_new - C; end
    else
        if Va_new > Va, Vref_new = Va_new - C;
        else,          Vref_new = Va_new + C; end
    end
    
    % UPDATE STATE
    Va = Va_new;
    Pa = Pa_new;
    
    % STORE FOR POST-ANALYSIS
    Va_array = [Va_array Va];
    Pa_array = [Pa_array Pa];
    Suns_array = [Suns_array Suns];
    
    % MOVE POINT ON P-V CURVE
    set(mppt_point,'XData',Va,'YData',Pa);
    drawnow;
    pause(0.05);
end

% ===== FIGURE 2: Evolution of V, P, and Irradiance =====
figure('Name','MPPT Performance Analysis');

subplot(3,1,1)
plot(Suns_array,'LineWidth',1.4,'Color',[0.9 0.6 0]), grid on
title('Solar Irradiance Profile')
ylabel('Irradiance (Suns)'), xlabel('Iteration')

subplot(3,1,2)
plot(Va_array,'LineWidth',1.4), grid on
title('PV Voltage (MPPT Tracking)')
ylabel('Voltage (V)'), xlabel('Iteration')

subplot(3,1,3)
plot(Pa_array,'LineWidth',1.4), grid on
title('PV Power (MPPT Tracking)')
ylabel('Power (W)'), xlabel('Iteration')

% ===== FIGURE 3: P(V) Trajectory =====
figure('Name','P-V Trajectory');
plot(Va_array, Pa_array,'LineWidth',2,'Color',[0.2 0.6 0.8]); grid on;
xlabel('Voltage (V)','FontSize',12);
ylabel('Power (W)','FontSize',12);
title('P(V) Trajectory Generated by P&O Algorithm','FontSize',14);

% Mark Maximum Power Point
[Pmax, idx] = max(Pa_array);
hold on;
plot(Va_array(idx), Pmax,'ro','MarkerSize',10,'MarkerFaceColor','r','LineWidth',2);
text(Va_array(idx), Pmax, sprintf('  Peak: %.2fW @ %.2fV', Pmax, Va_array(idx)), 'FontSize',11);

fprintf('Peak Power: %.2f W\n', Pmax);